services:
  - type: web
    name: pksyllabus-api
    env: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false # set in Render dashboard
      - key: DATA_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /api/health
